# docker build . -t dwarka:1.0.0

FROM golang:1.19 as src
WORKDIR /app
ADD ./ /app
RUN make compile

FROM gcr.io/distroless/base-debian11
COPY --from=src /app/out/dwarka /bin/
ENTRYPOINT [ "/bin/dwarka" ]
EXPOSE 1410
CMD ["server"]

